name: pulchowk_login
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  connectivity_plus: ^5.0.2
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications: ^17.1.0
  fluttertoast: ^8.2.4
  get: ^4.6.6
  hive: ^4.0.0-dev.2
  http: ^1.2.0
  isar_flutter_libs: ^4.0.0-dev.13
  logger: ^2.2.0
  network_info_plus: ^5.0.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
